apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-for-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: apps
    repoURL: git@github.com:itayf287/ArgoCD.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
