apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxapp-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginxapp
            port:
              number: 80
