apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxapp-ingress
spec:
  rules:
  - host: "footest22.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginxapp-svc
            port:
              number: 80
