apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-app
spec:
  ingressClassName: zeus
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginxapp
            port:
              number: 80
