apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxapp2
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  source:
    path: apps/data1
    repoURL: git@github.com:itayf287/ArgoCD.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  
    automated:
      selfHeal: true
