apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxapp1
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  source:
    path: apps/data
    repoURL: https://github.com/itayf287/ArgoCD
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  
    automated:
      selfHeal: true
